name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: |
          # Place ici ta commande de build si besoin, sinon supprime cette section
          echo "Build step"

      - name: Deploy to production branch
        run: |
          git config user.name "tonio28"
          git config user.email "a.chauveau87@gmail.com"
          git checkout --orphan production
          git rm -rf .
          cp index.html css/main.min.css script.min.js -r assets .
          git add .
          git commit -m "Deploy production"
          git push -f origin production